
[[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 2

# [[main]]
#   identifier = "gallery"
#   name = "有图"
#   url = "gallery"
#   weight = 3
#
# [[main]]
#   parent = "gallery"
#   name = "随拍"
#   url = "gallery/mine"
#
# [[main]]
#   parent = "gallery"
#   name = "截句"
#   url = "gallery/quote"

  [[main]]
    identifier = "showcase"
    name = "仓库"
    url = "showcase"
    weight = 4

 # [[main]]
 #    identifier = "publication"
 #    name = "白板"
 #    url = "publication"
 #    weight = 5

[[main]]
   identifier = "about"
   name = "关于"
   url = "about"
   weight = 6

[[main]]
  identifier = "friend"
  name = "友链"
  url = "friend"
  weight = 7
